version: "3"
services:
  hashgraphnodeone:
    build: "./"
    links:
        - couchdb:couchdb
    depends_on:
      - couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "52204:52204"
    networks:
      static-network:
        ipv4_address: 172.255.128.1
  hashgraphnodetwo:
    build: "./"
    links:
          - couchdb:couchdb
    depends_on:
      - couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "52205:52205"
    networks:
      static-network:
        ipv4_address: 172.255.128.2
  couchdb:
    image: couchdb:2.1
    ports:
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    networks:
        static-network:
          ipv4_address: 172.255.128.3
  swagger:
    image: "swaggerapi/swagger-ui"
    depends_on:
      - hashgraphnodeone
      - hashgraphnodetwo
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://0.0.0.0:52204/swagger.json
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.255.0.0/16