version: "3"
services:
  hashgraph1:
    container_name: "app1"
    build: "./"
    links:
      - couchdb:couchdb
    depends_on:
      - couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    networks:
      static-network:
        ipv4_address: 172.255.128.1
    ports:
      - "50204:50204"
      - "52204:52204"
  hashgraph2:
    container_name: "app2"
    build: "./"
    links:
      - couchdb:couchdb
    depends_on:
      - couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    networks:
      static-network:
        ipv4_address: 172.255.128.2
    ports:
      - "50205:50205"
  couchdb:
    image: couchdb:2.1
    ports:
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
  swagger:
    build: "./supporting-services/swagger-ui-master/"
    depends_on:
      - hashgraph1
      - hashgraph2
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "8080:8080"
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.255.0.0/16