version: "3"
services:
  hashgraph:
    build: "./"
    links:
      - couchdb:couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "51200-51299:51200-51299"
      - "52200-52299:52200-52299"
  couchdb:
    image: couchdb:2.1
    ports:
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
