version: "3"
services:
  hashgraph:
    build: "./"
    links:
      - couchdb:couchdb
    depends_on:
          - couchdb
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "52204-52207:52204-52207"
  couchdb:
    image: couchdb:2.1
    ports:
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
  swagger:
    build: "./supporting-services/swagger-ui-master/"
    depends_on:
      - hashgraph
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "8080:8080"